/** Produce the final human-readable inventory after the complete audit. */
import {join} from 'node:path';
const root=join(import.meta.dir,'../../..');
const slate=await Bun.file(join(import.meta.dir,'../data/bothin-to-muir-beach.spots.json')).json();
const audit=await Bun.file(join(import.meta.dir,'../data/bothin-muir-research/audit.json')).json();
if(audit.ready!==100||audit.errors.length||audit.invalidGeometry||audit.uncoveredSamples)throw Error('Complete clean 100-story audit required');
const counts=Object.fromEntries([...new Set(slate.spots.map((s:any)=>s.kind))].map(k=>[k,slate.spots.filter((s:any)=>s.kind===k).length]));
const light=slate.spots.filter((s:any)=>s.sources.some((u:string)=>new URL(u).hostname.endsWith('ptreyeslight.com'))).length;
const nps=slate.spots.filter((s:any)=>s.sources.some((u:string)=>new URL(u).hostname.endsWith('nps.gov'))).length;
const phoneFile=Bun.file(join(import.meta.dir,'../data/bothin-muir-research/phone-download.json'));
const phone=await phoneFile.exists()?await phoneFile.json():null;
const phoneStatus=phone?.verified===true
 ? `The complete offline pack was copied to iPhone minnow and verified: ${phone.recordings} recordings, transcripts, and location triggers.`
 : 'The complete offline pack is prepared and validated against the app’s Swift models. Transfer to iPhone minnow is pending because the device is unavailable to the Mac.';
let md=`# Bothin to Muir Beach via 101 and Tam Junction\n\nPublished September 13, 2026. **100 stories, ${audit.spokenMinutes.toFixed(1)} minutes of ElevenLabs recordings**, researched by 100 individual subagents after the full candidate list was identified.\n\nEnable **${slate.track.name}** in GrandTour; use Driving and Wander. The track is a series: heard stories retire from automatic playback. Download the track in the app for offline listening.\n\nRoute: 300 Bothin Road → Olema Road → Fairfax/Broadway → Center Boulevard → Red Hill Avenue → Fourth Street in San Rafael → US 101 south → Shoreline Highway through Manzanita and Tam Junction → Pacific Way → Muir Beach parking lot. The mapped route is ${(audit.routeDistanceM/1609.344).toFixed(1)} miles. OSRM's baseline estimate is ${audit.routeBaselineMinutes.toFixed(1)} minutes, excluding live traffic.\n\nThis is a dense collection of alternatives, not a promise to play all 100 stories on one drive. Fourteen overlapping listening areas cover the road. Nearby sites such as Muir Woods, downtown Mill Valley, Tennessee Valley, and the Muir Beach Overlook are explicitly identified as nearby or beyond the destination in their scripts. No detours are built into the route. The polygons describe listening relevance, not official town or park boundaries.\n\nContent: ${counts.history??0} history, ${counts.nature??0} nature, ${counts.news??0} dated news, and ${counts['national-park']??0} national park stories. ${light} stories use Point Reyes Light reporting; ${nps} cite National Park Service sources. News retains report dates and distinguishes proposals from completed work. Original paraphrases link to their sources.\n\nAmerican narrators: Roger, Matilda, Bill, Sarah. No added inter-story silence in the files; the app controls gaps.\n\nVerification: all 100 spot/content pairs published; all audio fully decoded before publication; transcripts match authored scripts; UTF-8 and timing alignment checked; all recordings support HTTP byte-range requests. All ${audit.routeSamples} sampled route locations have published recordings available; minimum ${audit.minOptions} story options per sample. These checks do not establish actual-car audio performance. The phone was disconnected during preparation, so direct cache installation was not verified.\n\n[Open the track preview](http://localhost:5190/?track=${audit.trackId}) · [Full source slate](../server/scripts/data/bothin-to-muir-beach.spots.json) · [Route GeoJSON](../server/scripts/data/bothin-muir-research/route.geojson) · [Verification inventory](../server/scripts/data/bothin-muir-research/audit.json)\n\n## Story inventory\n\n| # | Story | Listening area | Length | Sources |\n|---|---|---|---:|---|\n`;
for(const s of slate.spots){const a=audit.records.find((r:any)=>r.id===s.id);md+=`| ${s.id} | ${s.title.replace(/\|/g,'/')} | ${s.zone} | ${Math.round(a.durationMs/1000)} sec | ${s.sources.map((u:string,i:number)=>`[${i+1}](${u})`).join(' · ')} |\n`;}
md+='\n## Reproduce\n\nRun from the repository root. The environment file is loaded by Bun; do not print its contents.\n\n```sh\nbun --env-file=.env server/scripts/build-bothin-muir.ts\n# Pass explicitly reviewed IDs to record-bothin-muir.ts; existing matching recordings skip.\nbun --env-file=.env server/scripts/audit-bothin-muir.ts --http\nbun --env-file=.env server/scripts/model-bothin-muir.ts\nbun server/scripts/document-bothin-muir.ts\n```\n';
md=md.replace('Download the track in the app for offline listening.',phoneStatus)
 .replace('The phone was disconnected during preparation, so direct cache installation was not verified.',phoneStatus);
await Bun.write(join(root,'docs/bothin-to-muir-beach.md'),md);
console.log(JSON.stringify({published:100,minutes:audit.spokenMinutes,counts,pointReyesLight:light,npsSources:nps,document:join(root,'docs/bothin-to-muir-beach.md')}));
